name:  PythÃ¶rhead lemmy test

on:
  push:
    branches:
      - lemmytest

jobs:
  build-n-publish:
    name: PythÃ¶rhead lemmytest
    runs-on: ubuntu-latest
    steps:
    - name: "âœ”ï¸ Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "ğŸ Set up Python 3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: "ğŸ¤– Announce on lemmy.dbzer0.com"
      run: |
          python -m pip install pythorhead
          ls -la
          python .github/publish_on_lemmy.py v0.xx.xx
