name:  PythÃ¶rhead lemmy test

on:
  push:
    branches:
      - lemmytest

jobs:
  build-n-publish:
    name: PythÃ¶rhead lemmytest
    runs-on: ubuntu-latest
    steps:
    - name: "ğŸ Set up Python 3.10"
      if: ${{ steps.release.outputs.version != '' }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: "ğŸ¤– Announce on lemmy.dbzer0.com"
      if: ${{ steps.release.outputs.version != '' }}
      run: |
          python -m pip install pythorhead
          python .github/publish_on_lemmy.py
